# database generated on 2025-10-03 21:14 GMT
!!omap
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/add-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - add
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/addi-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - addi
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/and-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - and
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/andi-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - andi
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/auipc-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - auipc
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/beq-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - beq
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bge-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - bge
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bgeu-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - bgeu
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/blt-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - blt
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bltu-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - bltu
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/bne-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - bne
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/fence-01.S:
    commit_id: 81c7a2b769baa2f33f40bc5455299b1362b5d125
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - fence
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/jal-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - jal
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/jalr-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - jalr
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lb-align-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - lb-align
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lbu-align-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - lbu-align
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lh-align-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - lh-align
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lhu-align-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - lhu-align
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lui-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - lui
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/lw-align-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - lw-align
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/misalign1-jalr-01.S:
    commit_id: 0c4cdffe19b1a48d9fec8590c8817af2ff924a37
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - misalign1-jalr
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/or-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - or
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/ori-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - ori
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sb-align-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - sb-align
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sh-align-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - sh-align
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sll-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - sll
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/slli-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - slli
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/slt-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - slt
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/slti-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - slti
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sltiu-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - sltiu
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sltu-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - sltu
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sra-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - sra
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/srai-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - srai
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/srl-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - srl
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/srli-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - srli
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sub-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - sub
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/sw-align-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - sw-align
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/xor-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - xor
        verify: []
- /mnt/c/Users/xiangmin/Desktop/TFG/simple_riscv_cpu/riscv-arch-test/riscv-test-suite/rv32i_m/I/src/xori-01.S:
    commit_id: b91f98f3a0e908bad4680c2e3901fbc24b63a563
    isa:
    - RV32I
    parts: !!omap
    - '0':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        define:
        - def TEST_CASE_1=True
        mac: []
        coverage_labels:
        - xori
        verify: []
